In [1]:
import numpy as np
%load_ext autoreload
%autoreload 2

In [11]:
train_chord_path = "./trainData/chords/"
train_melody_path = "./trainData/melody/"

In [40]:
from PianoRoll import PianoRoll

In [29]:
chord_roll = PianoRoll(train_chord_path, res_factor=24)
melody_roll = PianoRoll(train_melody_path, res_factor=24)
print(chord_roll.ticks, chord_roll.max_note, chord_roll.min_note)
print(melody_roll.ticks, melody_roll.max_note, melody_roll.min_note)

(128, 59, 48)
(128, 83, 60)


In [6]:
#Test the Chord piano roll
x = chord_roll.generate_piano_roll_func()
y = chord_roll.generate_piano_roll()
print(x.shape)
print(y.shape)
np.testing.assert_equal(x, y)

(68, 128, 12)
(68, 128, 12)


In [15]:
# Test the melody piano roll
x = melody_roll.generate_piano_roll_func()
y = melody_roll.generate_piano_roll()
print(x.shape)
print(y.shape)
np.testing.assert_equal(x, y)

(68, 128, 24)
(68, 128, 24)


In [43]:
#Test Train and Test samples
chord_data = chord_roll.generate_piano_roll()
chord_double = PianoRoll.doubleRoll(chord_data)
mel_data = melody_roll.generate_piano_roll()
mel_double = PianoRoll.doubleRoll(mel_data)

ip_data, tar_data = PianoRoll.createNetInputs(chord_double, mel_double, seq_length=128)
y_ip, y_tar = PianoRoll.generate_samples(chord_data, mel_data, seq_length=128)
np.testing.assert_equal(ip_data, y_ip)
np.testing.assert_equal(tar_data, y_tar)

(68, 128, 12)


# Old Tests

In [24]:
# Test tile
x = np.arange(75).reshape((5,3,5))
y = np.tile(x,(1,2,1))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]

 [[45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]]


In [7]:
# #Note On OFF Array Test - Shape
# from mido import MidiFile
# configs = {
#             "res_factor":train_obj.res_factor,
#             "max_note": train_obj.max_note,
#             "min_note": train_obj.min_note
#         }
# x = PianoRoll.get_note_info(train_obj.files[0], configs)
# y = PianoRoll.getNoteTimeOnOffArray(MidiFile(train_obj.files[0]), train_obj.res_factor)
# y = np.array(y)
# np.testing.assert_almost_equal(x, y)

In [8]:
# notes = x.T[0]
# for i in range(train_obj.min_note, train_obj.max_note + 1):
#     print("{}\t{}\t{}".format(i, (notes == i).sum(), ((notes == i).sum() % 2) == 0))

In [9]:
# c = [np.array(np.arange(200).reshape(2,10,10)), np.array(np.arange(200).reshape(2,10,10))]
# np.vstack(c).shape

In [10]:
# x = PianoRoll.get_note_info(train_obj.files[0], configs)
# y_temp = PianoRoll.getNoteTimeOnOffArray(MidiFile(train_obj.files[0]), train_obj.res_factor)
# y = PianoRoll.getNoteOnLengthArray(y_temp)
# np.testing.assert_almost_equal(x,y)